#!/usr/bin/env bash
# Write the same Kettle app WITHOUT any Scry capture setup into <dest>.
# It is generated, never committed, so it cannot drift from the app. It is the "before" for the
# Scry skill (scry-native-capture-setup) and a fixture for trying capture setup by hand.
#
# Removed: capture mode (src/capture.ts, EXPO_PUBLIC_SCRY_CAPTURE), the dev-only probe
# (.rnstorybook/scryProbe.tsx), the scry-root testIDs, the capture script, the Scry workflow,
# evidence/ and the Scry README. The Storybook stories and the app itself are unchanged.
# Usage: scripts/make-bare.sh <dest>      (dest must not exist or must be empty)
set -euo pipefail

[ $# -eq 1 ] || { echo "usage: $0 <dest>" >&2; exit 2; }
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dest="$1"
mkdir -p "$dest"
if [ -n "$(ls -A "$dest")" ]; then echo "make-bare: $dest is not empty" >&2; exit 1; fi
dest="$(cd "$dest" && pwd)"
[ "$dest" != "$root" ] || { echo "make-bare: dest is the sample itself" >&2; exit 1; }

# 1. copy the source, leaving out installs, generated native folders and git history
tar -C "$root" \
  --exclude=./node_modules --exclude=./.git --exclude=./ios --exclude=./android \
  --exclude=./.expo --exclude=./.scry --exclude=./dist -cf - . | tar -C "$dest" -xf -

cd "$dest"

# 2. remove the Scry-only files
rm -rf src/capture.ts .rnstorybook/scryProbe.tsx scripts/capture-stories.mjs \
  scripts/make-bare.sh scripts/check-workflows.sh .github/workflows/scry-capture.yml evidence

# 3. take capture mode out of the code that used it (perl -i works the same on Linux and macOS)
perl -0pi -e '
  s/^import \{[^}]*\} from \x27(\.\.\/|\.\/)(src\/)?capture\x27;\n//mg;
  s/^import \{ ScryProbe \} from \x27\.\/scryProbe\x27;\n//mg;
  s/^[ \t]*testID=\{SCRY_ROOT_TEST_ID\}\n//mg;
  s/ testID=\{SCRY_ROOT_TEST_ID\}//g;
  s/^[ \t]*\{\.\.\.pressFeedback\}\n//mg;
  s/ \{\.\.\.pressFeedback\}//g;
' src/Screen.tsx src/components/*.tsx .rnstorybook/preview.tsx .rnstorybook/index.tsx
perl -0pi -e '
  s/^[ \t]*\/\/ Capture builds hide the on-device.*?\n[ \t]*\/\/ the story fills.*?\n[ \t]*onDeviceUI: !CAPTURE_MODE,\n//ms;
' .rnstorybook/index.tsx
perl -0pi -e '
  s/^[ \t]*\/\/ Capture builds: no safe-area padding.*?\n[ \t]*\/\/ display and is not clipped.*?\n[ \t]*noSafeArea: CAPTURE_MODE,\n//ms;
  s/^[ \t]*\/\/ Capture builds only \(EXPO_PUBLIC_SCRY_CAPTURE=1\).*?\n[ \t]*\/\/ asks for the story.*?\n//ms;
  s/decorators: \[withSafeArea, \.\.\.\(CAPTURE_MODE.*?\],\n/decorators: [withSafeArea],\n/ms;
' .rnstorybook/preview.tsx

# 4. a short README for the bare copy
cat > README.md <<'README'
# Kettle (bare)

The Kettle sample app without any Scry capture setup, generated by `scripts/make-bare.sh` from
`scry-sample-rn`. It runs and has on-device Storybook stories; it has no capture mode, no
`scry-root` test ids and no Scry workflow.

```sh
npm install
npm run storybook-generate
npm run android        # or: npm run ios
```

To set it up for Scry capture, ask your AI assistant "set up Scry capture for this app" with the
`scry-native-capture-setup` skill installed, or follow the steps in `scry-sample-rn`'s README.
README

# 5. no Scry words left in code or config (the README above names the tool on purpose)
if grep -rniE 'scry-root|SCRY_CAPTURE|scryProbe|pressFeedback|SCRY_ROOT_TEST_ID' \
     --include=*.ts --include=*.tsx --include=*.mjs --include=*.js --include=*.json --include=*.yml \
     --exclude=package-lock.json . ; then
  echo "make-bare: Scry capture references remain (see above)" >&2
  exit 1
fi
echo "wrote bare Kettle app to $dest"
