/* do not change this file, it is auto generated by storybook. */
/// <reference types="@storybook/react-native/metro-env" />
import { start, updateView, type View, type Features } from '@storybook/react-native';




const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./src/components",
    files: "**/*.stories.?(ts|tsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
    req: require.context(
      '../src/components',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/
    ),
  },
  {
    titlePrefix: "",
    directory: "./src/screens",
    files: "**/*.stories.?(ts|tsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
    req: require.context(
      '../src/screens',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/
    ),
  }
];


declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
  var STORYBOOK_WEBSOCKET:
    | { host?: string; port?: number; secured?: boolean }
    | undefined;
  var FEATURES: Features;
}


const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview")
];

globalThis.STORIES = normalizedStories;
globalThis.STORYBOOK_WEBSOCKET = {
  host: '192.168.0.152',
  port: 7007,
  secured: false,
};

module?.hot?.accept?.();

const options = {}

if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,
    options,
  });
} else {
  updateView(globalThis.view, annotations, normalizedStories, options);
}

export const view: View = globalThis.view;
